"use client";
import {useState} from "react";
const caps=[["认识你","身份与场景连续","知道此刻正在陪伴谁，也知道你正处在怎样的家庭场景。"],["记得你","经历与承诺延续","把重要的人、事、偏好与约定沉淀为可管理的长期记忆。"],["理解你","情绪与意图判断","结合语言、语气、表情与情境，判断回应、询问或保持安静。"],["陪着你","表达与行动","用数字人的语言、表情和动作回应，也能连接设备与家庭服务。"]];
const faqs=[["和智能音箱有什么不同？","智能音箱通常完成一次指令；灵伴拥有持续身份、长期记忆与关系状态，能够跨会话理解用户，并在合适时机主动陪伴。"],["会一直录音或监控家人吗？","不会。产品按最小必要原则使用麦克风、摄像头与传感器，并提供清晰的状态提示、权限开关和记忆删除能力。"],["底层大模型可以更换吗？","可以。大模型是通用能力底座，灵伴智能体中枢负责身份、记忆、决策、工具调用、安全与数字人表达。"]];
export default function Home(){const[open,setOpen]=useState(0);return <main>
 <nav className="nav wrap"><a className="brand" href="#top"><i>∞</i>灵伴</a><div><a href="#position">产品定位</a><a href="#experience">陪伴体验</a><a href="#platform">智能体中枢</a><a href="#trust">安全与隐私</a></div><a className="btn small" href="#contact">预约体验</a></nav>
 <section className="hero wrap" id="top"><div className="heroCopy"><small>LINGBAN · FAMILY AI COMPANION</small><h1>有记忆、懂情绪、<br/><em>能陪伴的 AI 数字家人</em></h1><p>不是给硬件增加一个聊天模型，而是让每台设备承载一个持续存在的 Agent 个体——认识你、记得你、理解你，也能陪你行动。</p><div className="actions"><a className="btn" href="#experience">看看它如何陪伴</a><a href="#platform">了解灵伴智能体中枢 →</a></div><div className="proof"><span>✓ 跨会话长期记忆</span><span>✓ 多模态情绪理解</span><span>✓ 数字人自然表达</span></div></div><div className="heroArt"><div className="glow"/><div className="device"><header><b>●</b> 灵伴正在陪你 <span>•••</span></header><div className="person"><div className="hair"/><div className="head"><i/><i/><b/></div><div className="body"/></div><p>欢迎回家。今天看起来有点累，要先休息一会儿吗？</p><footer>▮ ▮▮ ▮▮▮ ▮▮ ▮</footer></div><aside className="memo"><small>长期记忆</small><b>记得你周四要复诊</b><span>刚刚更新</span></aside><aside className="mood"><small>情绪感知</small><b>疲惫 · 需要安静陪伴</b><span>语音 + 表情 + 情境</span></aside></div></section>
 <section className="section wrap" id="position"><div className="heading"><small>01 · 产品定位</small><h2>从每次重新聊天，升级为<br/>长期记住并持续陪伴</h2><p>真正的产品不是一次回答，而是一段能够持续积累的关系。</p></div><div className="compare"><article className="old"><small>传统聊天硬件</small><h3>唤醒 → 提问 → 回答 → 结束</h3><p>被动响应 · 单次会话</p><ul><li>没有持续身份</li><li>没有长期记忆</li><li>每次交互都像第一次见面</li></ul></article><div className="up">升级为 <b>→</b></div><article className="new"><small>持续存在的 AI 数字家人</small><div>{caps.map((c,i)=><span className={"c"+i} key={c[0]}><b>{c[0]}</b><em>{c[1]}</em></span>)}</div><footer>数字人表达 × 实体设备 × 家庭服务 <b>越用越懂你</b></footer></article></div></section>
 <section className="section soft" id="experience"><div className="wrap"><div className="heading center"><small>02 · 陪伴体验</small><h2>不是更会说，而是真的更懂你</h2><p>灵伴把感知、记忆、理解与行动，串成一个完整陪伴闭环。</p></div><div className="capGrid">{caps.map((c,i)=><article key={c[0]}><small>0{i+1}</small><h3 className={"c"+i}>{c[0]}</h3><b>{c[1]}</b><p>{c[2]}</p></article>)}</div><div className="flow"><header><small>一次陪伴如何发生</small><b>从你走进家门，到它做出合适回应</b></header><div>{["感知你和环境","理解情绪与意图","读取记忆与关系","决定回应或行动","表达、服务并成长"].map((x,i)=><span key={x}><i>{i+1}</i>{x}{i<4&&<b>→</b>}</span>)}</div></div></div></section>
 <section className="section story wrap"><div><small className="blue">真实的一天 · 20:10</small><h2>它记得的不只是信息，<br/>还有共同生活的上下文</h2><p>回到家，灵伴识别出是你，也注意到你语速变慢。它没有立刻追问，而是结合日程和最近的睡眠状态，先给你留出一点安静。</p><aside>✓ <b>关系在延续</b><span>“上次你压力大时，更希望先安静一会儿。”</span></aside></div><div className="chat"><header><i>灵</i><b>灵伴</b><small>在客厅 · 在线</small></header><p>欢迎回家。今天辛苦了，要不要先把灯光调暗一点？</p><p>嗯，先安静一会儿吧。</p><footer>⌁ <b>已调暗客厅灯光</b><span>记住：今晚需要安静陪伴</span></footer></div></section>
 <section className="section platform" id="platform"><div className="wrap"><div className="heading dark"><small>03 · 产品核心</small><h2>大模型提供通用能力，<br/>智能体中枢把能力组织成产品</h2><p>模型可以更换；身份、关系、记忆、场景数据与评测体系会持续积累。</p></div><div className="diagram"><article><small>外部通用能力</small><h3>模型与云服务</h3><span>LLM 理解与生成</span><span>视觉 / 语音模型</span><span>ASR / TTS</span></article><b>组织成产品 →</b><article className="brain"><small>我们自主研发</small><h3>灵伴智能体中枢</h3><div><span><b>Agent 运行与编排</b>路由、任务、工具、恢复</span><span><b>长期记忆与关系</b>写入、检索、纠错、遗忘</span><span><b>角色与具身表达</b>人格、情绪、行为、数字人</span><span><b>安全、评测与运营</b>权限、日志、回放、指标</span></div></article><b>形成体验 →</b><article className="result"><small>用户获得</small><h3>持续存在的 AI 数字家人</h3><span>✓ 认识我</span><span>✓ 记得我</span><span>✓ 理解我</span><span>✓ 能行动</span></article></div><div className="assets"><b>真正沉淀的产品资产</b><span>智能体系统</span><span>用户关系</span><span>场景数据</span><span>评测体系</span></div></div></section>
 <section className="section wrap" id="trust"><div className="trust"><div><small className="blue">04 · 安全与隐私</small><h2>亲近感的前提，<br/>是边界始终清晰</h2><p>每次交互都经过身份确认、数据权限、内容安全与操作风险校验；结果可追溯、可纠正、可撤销。</p></div><div>{[["权限透明","相机、麦克风、记忆和设备控制都有明确授权与状态提示。"],["记忆可控","支持查看、纠错、遗忘与删除，不把所有信息都变成长记忆。"],["家庭保护","按成员身份配置能力边界，高风险动作需二次确认。"],["全链路可追溯","关键决策、工具调用与结果都有日志、回放和评测。"]].map((x,i)=><article key={x[0]}><small>0{i+1}</small><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></div></section>
 <section className="section faq wrap"><div><small className="blue">常见问题</small><h2>你可能还想知道</h2></div><div>{faqs.map((f,i)=><button onClick={()=>setOpen(open===i?-1:i)} key={f[0]}><span><b>{f[0]}</b><em>{open===i?"−":"+"}</em></span>{open===i&&<p>{f[1]}</p>}</button>)}</div></section>
 <section className="cta wrap" id="contact"><div><small>灵伴 AI 数字家人</small><h2>让 AI 不只回答你，<br/>而是真正陪伴你。</h2><p>面向家庭长期陪伴场景，打造有身份、有记忆、能行动的 AI 伙伴。</p></div><a className="btn white" href="mailto:hello@lingban.ai">预约产品体验</a></section>
 <footer className="footer wrap"><a className="brand" href="#top"><i>∞</i>灵伴</a><p>有记忆、懂情绪、能陪伴的 AI 数字家人</p><span>© 2026 Lingban AI</span></footer>
 </main>}
